"""Stable locators for Franchisee Accounts (staging 2026-07-24). Prefer CSS/text over absolute XPath."""

franchise_path = {
    "search_box_name": "code",
    "search_box_css": 'input[name="code"][placeholder*="Find by franchise"]',
    "name_search_result_path": "//table//tbody/tr[1]/td[1]",
    "email_search_result_path": "//table//tbody/tr[1]/td[2]",
    "entity_name_search_result_path": "//table//tbody/tr[1]/td[3]//p[1]",

    # listing actions — first data row
    "list_three_dots_action_btn_pth": "//table//tbody/tr[1]//td[last()]//div[contains(@class,'actions-column')]//button",
    "list_set_as_inactive": "//*[contains(normalize-space(.),'Set as inactive') or contains(normalize-space(.),'Inactive')]",
    "yes_set_as_in_active": "//button[contains(.,'Yes') or contains(.,'Confirm')]",
    "check_status_path": "//table//tbody/tr[1]/td[5]",
    "list_set_as_active": "//*[contains(normalize-space(.),'Set as active') or contains(normalize-space(.),'Active')]",
    "yes_set_as_active": "//button[contains(.,'Yes') or contains(.,'Confirm')]",

    "row_per_page_select_box_path": "//select[@title='pageSize']",
    "10_row_per_page_path": "//select[@title='pageSize']/option[@value='10']",
    "20_row_per_page_path": "//select[@title='pageSize']/option[@value='20']",
    "50_row_per_page_path": "//select[@title='pageSize']/option[@value='50']",

    # pagination only appears when item count > page size
    "next_page_btn_path": "//table//tfoot//*[normalize-space()='2' or normalize-space()='>']",
    "prev_page_btn_path": "//table//tfoot//*[normalize-space()='1']",
    "page_1_btn_path": "//table//tfoot//*[normalize-space()='1']",
    "page_2_btn_path": "//table//tfoot//*[normalize-space()='2']",

    "add_new_franchise_btn_path": "//button[contains(.,'Add new franchise')]",

    "email_address_name": "email",
    "franchise_name": "name",
    "add_entity_btn_path": "//button[contains(.,'Add entity') or contains(.,'Add Entity')]",
    "delete_entity_btn": "//button[contains(.,'Delete') or contains(@aria-label,'Delete')]",
    "entity_name": "franchiseEntities.0.title",
    "uen_name": "franchiseEntities.0.entityNo",
    "outlet_owned_select_box_path": "//label[contains(.,'Outlet')]/following::button[@role='combobox'][1] | //button[@role='combobox'][1]",
    "select_outlet_name_check_box_path": "//ul//li//input[@type='checkbox'][1]",
    "updated_outlet_owned_value_path": "//ul//li//input[@type='checkbox'][2]",
    "rule_1_checkbox": "//button[@role='checkbox'][1]",
    "rule_2_checkbox": "//button[@role='checkbox'][2]",
    "acc_no_name": "accountNo",
    "acc_holder_name": "accountHolderName",
    "bank_name": "bankName",
    "sort_code_name": "sortCode",
    "bill_name": "billingName",
    "bill_email_name": "billingEmail",
    "country_code_btn_path": "//button[@role='combobox'][contains(.,'+') or contains(.,'65')]",
    "bill_mobile_no_name": "billingMobile",
    "company_name": "companyName",
    "country_dropdown_path": "//label[contains(.,'Country')]/following::button[@role='combobox'][1]",
    "selected_outlet_path": "//select/option[not(@disabled)][last()]",
    "updated_outlet_path": "//select/option[not(@disabled)][1]",
    "postal_or_zip_code_name": "postalCode",
    "company_address_path": "//textarea",
    "create_btn_path": "//footer//button[contains(.,'Create') or contains(.,'Save') or contains(.,'Publish')]",

    "invalid_email_err_msg_path": "//p[contains(.,'Invalid email')]",
    "req_email_err_msg_path": "//p[contains(.,'Email is required')]",
    "req_franchise_name_err_msg_path": "//p[contains(.,'Franchise name is required')]",
    "req_entity_name_err_msg_path": "//p[contains(.,'Entity name is required')]",
    "req_uen_err_msg_path": "//p[contains(.,'UEN is required')]",
    "req_outlet_owned_err_msg_path": "//p[contains(.,'outlet')]",
    "req_acc_no_err_msg_path": "//p[contains(.,'Account number is required')]",
    "req_acc_holder_name_err_msg_path": "//p[contains(.,'Account holder name is required')]",
    "req_bank_name_err_msg_path": "//p[contains(.,'Bank name is required')]",
    "req_sort_code_err_msg_path": "//p[contains(.,'Sort code is required')]",
    "req_billing_name_err_msg_path": "//p[contains(.,'Billing name is required')]",
    "invalid_billing_email_err_msg_path": "//p[contains(.,'Invalid email')]",
    "req_billing_email_err_msg_path": "//p[contains(.,'Billing email is required')]",
    "req_billing_mobile_err_msg_path": "//p[contains(.,'Billing mobile is required')]",
    "req_company_name_err_msg_path": "//p[contains(.,'Company name is required')]",
    "req_postal_code_err_msg_path": "//p[contains(.,'Postal code is required')]",
    "req_company_address_err_msg_path": "//p[contains(.,'Company address is required')]",

    "edit_btn_path": "//table//tbody/tr[1]//td[last()]//div[contains(@class,'actions-column')]//span[.//svg]",

    "more_action_btn_path": "//header//button[.//svg or contains(.,'More')]",
    "more_action_inactive_btn_path": "//*[contains(normalize-space(.),'Set as inactive') or contains(normalize-space(.),'Inactive')]",
    "more_action_active_btn_path": "//*[contains(normalize-space(.),'Set as active') or contains(normalize-space(.),'Active')]",
    "yes_btn_path": "//button[contains(.,'Yes') or contains(.,'Confirm')]",
}
